
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EPS LETTER LPAREN OR RPAREN STARE : E OR TE : TT : T FT : F F : LPAREN E RPARENF : F STARF : LETTERF : EPS'
    
_lr_action_items = {'LPAREN':([0,2,3,4,5,6,7,8,9,11,12,],[4,4,-4,4,-7,-8,4,-3,-6,4,-5,]),'LETTER':([0,2,3,4,5,6,7,8,9,11,12,],[5,5,-4,5,-7,-8,5,-3,-6,5,-5,]),'EPS':([0,2,3,4,5,6,7,8,9,11,12,],[6,6,-4,6,-7,-8,6,-3,-6,6,-5,]),'$end':([1,2,3,5,6,8,9,11,12,],[0,-2,-4,-7,-8,-3,-6,-1,-5,]),'OR':([1,2,3,5,6,8,9,10,11,12,],[7,-2,-4,-7,-8,-3,-6,7,-1,-5,]),'RPAREN':([2,3,5,6,8,9,10,11,12,],[-2,-4,-7,-8,-3,-6,12,-1,-5,]),'STAR':([3,5,6,8,9,12,],[9,-7,-8,9,-6,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'E':([0,4,],[1,10,]),'T':([0,4,7,],[2,2,11,]),'F':([0,2,4,7,11,],[3,8,3,3,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> E","S'",1,None,None,None),
  ('E -> E OR T','E',3,'p_E','regcomp.py',67),
  ('E -> T','E',1,'p_E1','regcomp.py',72),
  ('T -> T F','T',2,'p_T','regcomp.py',77),
  ('T -> F','T',1,'p_T1','regcomp.py',82),
  ('F -> LPAREN E RPAREN','F',3,'p_F','regcomp.py',87),
  ('F -> F STAR','F',2,'p_F1','regcomp.py',95),
  ('F -> LETTER','F',1,'p_F2','regcomp.py',100),
  ('F -> EPS','F',1,'p_F3','regcomp.py',105),
]
